### ISSUE TITLE
refactor unit tests for travis

### ISSUE THREAD

**Issue by nickcharron** [BEAMRobotics/libbeam#131]
Let's change the unit tests to have a script in each beam module that runs all tests so that:

1. the main travis file only has to call one script for each module so this would only need to be changed when new modules are created
2. we could run all the tests locally on our machine for a module by running one script. This would help testing a lot. If I make changes to CameraModel.cpp for example, I could run .../beam_calibration/run_all_tests.sh and make sure it didn't break any of the unit tests in the module
3. It would be easier to add new tests to CI because you're not editing a giant list, you're editing a file in the module you're working in 

So the structure would be something like this:

```
libbeam:
    .travis.yml:
         - cd $HOME/catkin_ws/src/libbeam/beam_calibration
         - ./run_all_tests.sh
         - cd $HOME/catkin_ws/src/libbeam/beam_cv
         - ./run_all_tests.sh
         - ...
libbeam/beam_calibration:
    run_all_tests.sh:
        -cd $HOME/catkin_ws/build/libbeam/beam_calibration
        - ./beam_calibration_extrinsics_tests
        - ./beam_calibration_radtan_tests
        ...
```
